# Generated by Django 4.2 on 2024-09-04 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=10)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('breed', models.CharField(max_length=100)),
                ('personality', models.TextField(blank=True, max_length=400, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='bird_profile/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
