# Generated by Django 4.2 on 2024-09-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bird'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
