# Generated by Django 4.2 on 2024-09-04 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_bird_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='birds', to=settings.AUTH_USER_MODEL),
        ),
    ]
